title: Mateusz Kapusta
email: mr.kapusta@student.uw.edu.pl
description: >- # this means to ignore newlines until "baseurl:"
  Astro/Physics/Math/CS, all in one.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: ""
github_username:  Wesenheit

# Build settings
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-mathjax-csp
markdown: kramdown

header_pages:
  - index.markdown
  - about.markdown
  - publications.markdown # Add your new page here
